### ISSUE TITLE
Specified values for fields "Name" and  "PhysicalContext" in Voltages 

### ISSUE THREAD

**Issue by ehaligow** [opencomputeproject/HWMgmt-OCP-Profiles#59]
In profiles the values for fields "Name" and  "PhysicalContext" in Votages are provided,   

```
"Voltages": [
			    {
				    "PropertyRequirements": {
					    "Name": "VRM1 Voltage",
					    "SensorNumber": {},
					    "Status": {},
				    	"ReadingVolts": {},
					    "PhysicalContext": "VoltageRegulator"
				    }
			    }
		    ],
```

Should those values be specified?

**Comment by jcleung5549** [comment]
Yes, they are specific.  One of the reasons the Power and Thermal model are being deprecated from PowerSubsystem and ThermalSubsystem.  The proposed baseline1.1 updates the baseline with PowerSubsystem and ThermalSubsystem - #50

**Comment by ehaligow** [comment]
I see, so the merge will resolve the issue.

**Comment by jcleung5549** [comment]
I may have read the issue incorrectly.  The values should be specified in the response from the managed node.  This means that the Voltages array object should have an element whose Name and Physical Context properties have the values specified.  The profile syntax is clunky when prescribing array elements.

**Comment by jcleung5549** [comment]
Fixed in v1.0.3

**Comment by ehaligow** [comment]
Hi, @jcleung5549 
I think we are still not on the same page, when in comes to this issue. The validator still returns an error, because the Voltage field has specified values for fields "Name" and "PhysicalContext". I understand, that the values for the fields are required specific, but I think it should be done differently - setting "Values" property, as done below: 
```
"Voltages": {
          "PropertyRequirements": {
             "Name": {
              "Values": [
                "VRM1 Voltage"
              ]
            },
             "SensorNumber": {},
             "Status": {},
             "ReadingVolts": {},
             "PhysicalContext": {
              "Values": [
                "VoltageRegulator"
              ]
            }
          }
	},
```
